# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rcavalie <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/24 10:40:22 by rcavalie          #+#    #+#              #
#    Updated: 2021/03/24 11:47:29 by rcavalie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


CFLAGS =-Wall -Werror -Wextra
SRCDIR =-I
SRC =$(addprefix ft_, $(addsuffix .c,\ isalpha\
	  isdigit\
	  isalnum\
	  isascii\
	  isprint\
))
all: $(

clean:
	/bin/rm -f *.o

fclean: clean
	bin.rm -f $(NAME)

re: fclean all
